# Generated by Django 2.1.7 on 2021-04-02 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210402_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 2, 15, 26, 19, 494865)),
        ),
    ]
